/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as ShifumiGameIdImport } from './routes/shifumi.$gameId'

// Create Virtual Routes

const ShifumiLazyImport = createFileRoute('/shifumi')()
const IndexLazyImport = createFileRoute('/')()

// Create/Update Routes

const ShifumiLazyRoute = ShifumiLazyImport.update({
  id: '/shifumi',
  path: '/shifumi',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/shifumi.lazy').then((d) => d.Route))

const IndexLazyRoute = IndexLazyImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const ShifumiGameIdRoute = ShifumiGameIdImport.update({
  id: '/$gameId',
  path: '/$gameId',
  getParentRoute: () => ShifumiLazyRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/shifumi': {
      id: '/shifumi'
      path: '/shifumi'
      fullPath: '/shifumi'
      preLoaderRoute: typeof ShifumiLazyImport
      parentRoute: typeof rootRoute
    }
    '/shifumi/$gameId': {
      id: '/shifumi/$gameId'
      path: '/$gameId'
      fullPath: '/shifumi/$gameId'
      preLoaderRoute: typeof ShifumiGameIdImport
      parentRoute: typeof ShifumiLazyImport
    }
  }
}

// Create and export the route tree

interface ShifumiLazyRouteChildren {
  ShifumiGameIdRoute: typeof ShifumiGameIdRoute
}

const ShifumiLazyRouteChildren: ShifumiLazyRouteChildren = {
  ShifumiGameIdRoute: ShifumiGameIdRoute,
}

const ShifumiLazyRouteWithChildren = ShifumiLazyRoute._addFileChildren(
  ShifumiLazyRouteChildren,
)

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/shifumi': typeof ShifumiLazyRouteWithChildren
  '/shifumi/$gameId': typeof ShifumiGameIdRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/shifumi': typeof ShifumiLazyRouteWithChildren
  '/shifumi/$gameId': typeof ShifumiGameIdRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexLazyRoute
  '/shifumi': typeof ShifumiLazyRouteWithChildren
  '/shifumi/$gameId': typeof ShifumiGameIdRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/shifumi' | '/shifumi/$gameId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/shifumi' | '/shifumi/$gameId'
  id: '__root__' | '/' | '/shifumi' | '/shifumi/$gameId'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  ShifumiLazyRoute: typeof ShifumiLazyRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  ShifumiLazyRoute: ShifumiLazyRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/shifumi"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/shifumi": {
      "filePath": "shifumi.lazy.tsx",
      "children": [
        "/shifumi/$gameId"
      ]
    },
    "/shifumi/$gameId": {
      "filePath": "shifumi.$gameId.tsx",
      "parent": "/shifumi"
    }
  }
}
ROUTE_MANIFEST_END */
